export type RootStackParamList = {
  Login: undefined;
  Register: undefined;
  Dashboard: undefined;
  ShareAccount: undefined;
  Perfil: undefined;
  Settings: undefined;
  EstufasList: { mode?: 'colheita' | 'manejo' } | undefined;
  EstufaForm: { estufaId?: string } | undefined;
  EstufaDetail: { estufaId: string };
  EstufaHistory: { estufaId: string } | undefined;
  PlantioForm: { plantioId?: string; estufaId?: string } | undefined;
  PlantioDetail: { plantioId: string };
  PlantioHistory: { plantioId: string; estufaId?: string } | undefined;
  ManejoForm: { plantioId?: string; estufaId?: string } | undefined;
  ManejosHistory: { plantioId: string; estufaId?: string } | undefined;
  ColheitaForm: { plantioId?: string; estufaId?: string; vendaId?: string; isEdit?: boolean } | undefined;
  VendasList: undefined;
  ContasReceber: undefined;
  AplicacaoForm: { plantioId?: string; estufaId?: string } | undefined;
  AplicacoesHistory: { plantioId: string; estufaId?: string } | undefined;
  InsumosList: undefined;
  InsumoForm: { insumoId?: string } | undefined;
  InsumoEntry: { preselectedInsumoId?: string } | undefined;
  FornecedoresList: undefined;
  FornecedorForm: { fornecedorId?: string } | undefined;
  ClientesList: undefined;
  ClienteForm: { clienteId?: string } | undefined;
  DespesasList: undefined;
  DespesaForm: { despesaId?: string } | undefined;
  Relatorios: undefined;
  RelatorioOperacional: undefined;
  Tarefas: undefined;
};
